# Commitizen config file
# https://commitizen-tools.github.io/commitizen/

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.1.0"
version_provider = "commitizen"
tag_format = "v$version"
update_changelog_on_bump = true
