---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# run 'pre-commit install' after changes

repos:
  
  # Check pre-commit messages
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
